cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LeftWrist2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/RightWrist2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LThumb1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LThumb1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LThumb2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LThumb2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LThumb3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LThumb3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LIndex1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LIndex1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LIndex2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LIndex2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LIndex3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LIndex3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LMiddle1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LMiddle1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LMiddle2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LMiddle2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LMiddle3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LMiddle3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LRing1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LRing1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LRing2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LRing2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LRing3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LRing3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LLittle1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LLittle1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LLittle2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LLittle2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LLittle3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/LLittle3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Thumb1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Thumb1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Thumb2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Thumb2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Thumb3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Thumb3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Index1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Index1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Index2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Index2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Index3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Index3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Middle1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Middle1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Middle2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Middle2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Middle3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Middle3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Ring1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Ring1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Ring2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Ring2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Ring3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Ring3_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Little1.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Little1_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Little2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Little2_2.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Little3.obj .
cp ../../../mocap_manipulation/bvh_files/2/2_skel_glove_forHandIK_reduced_sd/Little3_2.obj .
